### ISSUE TITLE
Disambiguation in "Closes xyz" vs "Fixes xyz"

### ISSUE THREAD

**Issue by naman1901** [coala/documentation#465] opened 2017-08-27 08:34 UTC
I think the docs need to be clearer as to when to use Fixes and when to use Closes. Whenever I use one, someone asks me to change to the other. As a result, I had to change the verb multiple times on the same issue. I feel that much of the community itself isn't very clear about this usage. This needs to be discussed.

**Comment by Makman2** [comment] 2017-08-27 14:56
Quoting from https://github.com/coala/coala-bears/pull/1767#issuecomment-325202707

> every issue that is tagged with bug is referred to with "Fixes", while other issues get a "Closes". This is no bug in terms of code-problems, but a simple documentation enhancement.

Bugs are defined as code-problems, like "a function shall not throw an exception when I give 3 as input". Everything else aren't bugs :)

Though for newcomers, the main guideline is: If an issue is labeled as a `bug`, use `Fixes XXXX`. If it's not labeled as `bug`, use `Closes`.

So yeah let's clarify docs with that :)

**Comment by naman1901** [comment] 2017-08-27 14:57
Thanks! Appreciate your time :D

**Comment by HarshKhatore** [comment] 2017-09-03 22:51
@naman1901 Could you please guide me on this? I am a newcomer.

**Comment by Makman2** [comment] 2017-09-04 16:00
Yes :+1:

**Comment by HarshKhatore** [comment] 2017-09-04 17:44
@Makman2 How should I approach this issue and where to find the required file?

**Comment by Makman2** [comment] 2017-09-04 18:07
Explain when to use `Fixes` vs `Closes` better (see above) in the according part of the newcomers guide. The according doc file is at https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst

**Comment by HarshKhatore** [comment] 2017-09-05 05:29
I was thinking of replacing 'fix' in the document with 'resolve' and keeping the 'close' word as they are at the places they appear, in the document. And, then specify how to mention 'Closes xyz' or 'Fixes xyz' in the pull request section. Would that be good? @Makman2 @naman1901

**Comment by Makman2** [comment] 2017-09-05 13:20
Not sure what you mean, however you can just do what you think is best and open a PR, then I can see what you have in mind :)

**Comment by RaiVaibhav** [comment] 2017-10-04 12:10
@Makman2 @naman1901 can i work on this??issue sir , one more thing sir why travis and circle CI,failed on documentation

**Comment by Makman2** [comment] 2017-10-04 14:07
@RaiVaibhav as you see the issue is already assigned :)

**Comment by RaiVaibhav** [comment] 2017-10-04 14:10
@Makman2 as  last updated 26 days ago so i asked

**Comment by Makman2** [comment] 2017-10-04 14:11
yeah in this case the PR wasn't reviewed further, I'm doing that right now. Let's see what happens now :)
Feel free to take another issue :)

**Comment by RaiVaibhav** [comment] 2017-10-04 14:14
@Makman2  sir i want to make some change on @HarshKhatore commit, as i can see the things he added will not get displayed as we want it to be

**Comment by Makman2** [comment] 2017-10-04 14:15
if he's not responding now in a few days, I'll reassign the issue to you :) Until then we should let him work on it again himself. But if you have ideas on how to explicitly improve things, feel free to drop comments at the PR :+1:

**Comment by HarshKhatore** [comment] 2017-10-04 16:46
Ya @RaiVaibhav, if you have any suggestions, I am eager to listen to them :)

**Comment by starlord1311** [comment] 2017-11-07 06:53
i am new to open source. can someone help me with what to do in this issue?

**Comment by Makman2** [comment] 2017-11-09 23:44
If you don't understand roughly what has to be done, it's better to pick another issue :)

**Comment by jayvdb** [comment] 2017-11-27 05:11
Marking as invalid, because this issue is in the wrong repository.
And low, as it requires someone who has done a few patches before they could properly do this issue.

**Comment by Makman2** [comment] 2017-11-27 19:26
Hmm I think this issue is valid in this repo, this info should imo go into `Newcomers_Guide.rst`^^

**Comment by prnvdixit** [comment] 2017-12-16 16:43
This issue would also include changes from https://github.com/coala/coala/issues/4769#issuecomment-338540088 :wink:
Also, @Makman2, "Newcomer's guide.rst" and "Writing_Good_Commits.rst" are in [coala/coala](https://github.com/coala/coala/tree/master/docs/Developers) - Right? :smile:

**Comment by Makman2** [comment] 2017-12-16 19:10
Oh indeed.

**Comment by Makman2** [comment] 2017-12-16 19:11
Migrated to https://github.com/coala/coala/issues/4976

**Closed by Makman2** 2017-12-16 19:11 UTC
Labels: difficulty/low, status/invalid
