### ISSUE TITLE
Documentation: Translation into Spanish Language 

### ISSUE THREAD

**Issue by michaelizer** [coala/documentation#527] opened 2018-02-07 14:39 UTC
Hello, I would love to contribute by translating all the documentation available into Spanish so people limited by the language can still involve in the project with no problems. Let me know what do you think?

By the way, should I make a new branch named ''Spanish translations'' or something?

Thank you in advance and keep up the good work!

**Comment by Makman2** [comment] 2018-02-09 20:02
@michaelizer hi :) Thanks for your offer :)
Please don't start yet, this has to be discussed. We regularly change parts inside our docs, so once we have an official translation it should be kept alive and up-to-date as long as possible :+1: We once had translations for the core tool `coala` itself, but we abandoned it because it was unmaintainable for us (missing translations, many languages, ...).

CC @jayvdb @sils 
What do you think about translating docs right now into a non-english language?

**Comment by Makman2** [comment] 2018-02-09 20:04
Oh this actually seems to be a duplicate of https://github.com/coala/documentation/issues/526

**Closed by Makman2** 2018-02-09 20:04 UTC
Labels: area/documentation, status/needs discussion

**Comment by michaelizer** [comment] 2018-02-10 14:42
Thank you Makman2, let me know when you have discussed this. Sorry for the Issue duplication
